"""
Gap Reporter — Generates publication-grade Markdown Competitive Analysis reports.
"""
from __future__ import annotations
import os
from urllib.parse import urlparse
from rankintel.models.schema import ComparisonReport

class GapReporter:
    """Renders ComparisonReport to formatted Markdown and saves to disk."""

    @classmethod
    def render(cls, report: ComparisonReport) -> str:
        dom_a = urlparse(report.target_a_url).netloc
        dom_b = urlparse(report.target_b_url).netloc
        winner_dom = urlparse(report.winner_url).netloc if report.winner_url != "TIE" else "TIE"

        lines = [
            f"# RANKINTEL COMPETITIVE GAP REPORT",
            f"**Target A:** {report.target_a_url} ({dom_a})",
            f"**Target B:** {report.target_b_url} ({dom_b})",
            f"**Date:** {report.timestamp}",
            f"**Analysis Platform:** RankIntel Multi-Engine Intelligence v2.0",
            "",
            "---",
            "",
            "## 🏆 HEAD-TO-HEAD SCORECARD",
            f"- **Overall Leader:** 🥇 **{winner_dom}**" if winner_dom != "TIE" else "- **Overall Result:** ⚖️ **Statistical Tie**",
            f"- **Health Gap:** {report.score_gap} points",
            f"- **{dom_a} Score:** {report.target_a_report.overall_health_score}/100",
            f"- **{dom_b} Score:** {report.target_b_report.overall_health_score}/100",
            "",
            "| Telemetry Domain | " + f"{dom_a}" + " | " + f"{dom_b}" + " | Advantage |",
            "|---|---|---|---|",
        ]

        for d in report.category_deltas:
            win_label = urlparse(d.winner).netloc if d.winner not in ("TIE", "") else "TIE"
            if win_label == dom_a:
                advantage = f"🟢 **{dom_a}**"
            elif win_label == dom_b:
                advantage = f"🔵 **{dom_b}**"
            else:
                advantage = "⚪ Tie"

            lines.append(f"| **{d.category}** | {d.target_a_val} | {d.target_b_val} | {advantage} |")

        lines.extend([
            "",
            "## 🎯 STRATEGIC GAP REMEDIATION ACTION PLAN",
            "*(Ranked in order of estimated competitive impact points)*",
            "",
        ])

        if not report.action_plan:
            lines.append("🟢 **No critical competitive gaps identified.** Both sites maintain comparable SEO and GEO hygiene.")
        else:
            for idx, act in enumerate(report.action_plan, 1):
                lines.extend([
                    f"### {idx}. [{act.priority}] {act.title} (+{act.impact_points} pts)",
                    f"- **Category:** `{act.category}`",
                    f"- **Winning Advantage:** {act.winning_advantage}",
                    f"- **Rationale:** {act.rationale}",
                    f"- **Recommended Fix:** {act.remediation_suggestion}",
                    "",
                ])

        lines.extend([
            "## 🛡️ TRUST STACK & E-E-A-T COMPARISON",
            f"| Trust Layer | {dom_a} | {dom_b} |",
            "|---|---|---|",
        ])

        layers_a = report.target_a_report.unified_trust.layers
        layers_b = report.target_b_report.unified_trust.layers
        for l_name, l_data_a in layers_a.items():
            l_data_b = layers_b.get(l_name)
            b_score = f"{l_data_b.score}/5" if l_data_b else "0/5"
            lines.append(f"| **{l_data_a.label}** | {l_data_a.score}/5 | {b_score} |")

        lines.extend([
            f"| **Total Trust Grade** | **{report.target_a_report.unified_trust.grade} ({report.target_a_report.trust_score}/100)** | **{report.target_b_report.unified_trust.grade} ({report.target_b_report.trust_score}/100)** |",
            "",
            "## 🤖 AI SEARCH CRAWLER ACCESS COMPARISON",
            f"| Bot Name | Role | {dom_a} | {dom_b} |",
            "|---|---|---|---|",
        ])

        bots_a = report.target_a_report.unified_robots.bot_access
        bots_b = report.target_b_report.unified_robots.bot_access
        all_bot_names = sorted(list(set(list(bots_a.keys()) + list(bots_b.keys()))))

        for bot_name in all_bot_names:
            status_a = bots_a.get(bot_name)
            status_b = bots_b.get(bot_name)
            icon_a = "🟢 ALLOWED" if status_a and status_a.status == "ALLOWED" else ("🔴 BLOCKED" if status_a and status_a.status == "BLOCKED" else "⚪ UNKNOWN")
            icon_b = "🟢 ALLOWED" if status_b and status_b.status == "ALLOWED" else ("🔴 BLOCKED" if status_b and status_b.status == "BLOCKED" else "⚪ UNKNOWN")
            role = status_a.role_or_purpose if status_a else (status_b.role_or_purpose if status_b else "")
            lines.append(f"| **{bot_name}** | {role[:35]} | {icon_a} | {icon_b} |")

        lines.extend([
            "",
            "---",
            "*Report generated by RankIntel Autonomous Multi-Engine Intelligence v2.0.*",
            ""
        ])

        return "\n".join(lines)

    @classmethod
    def save(cls, report: ComparisonReport, output_dir: str = "reports") -> str:
        """Render and save comparison report to disk."""
        os.makedirs(output_dir, exist_ok=True)
        dom_a = urlparse(report.target_a_url).netloc.replace(":", "_")
        dom_b = urlparse(report.target_b_url).netloc.replace(":", "_")
        filename = f"comparison-{dom_a}-vs-{dom_b}-{report.timestamp}.md"
        filepath = os.path.join(output_dir, filename)

        content = cls.render(report)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        return filepath
